version: '3.8'
services:
  e2e:
    image: "/cypress"
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: cypress
    # environment:
    # - CYPRESS_baseUrl=http://localhost:88
    command: >
        bash -c "npm run cy:clear && npm run cy:run:api && npm run cy:run:front"
    #network_mode: "host"
    volumes:
      - ./cypress:/cy/cypress
      - ./cypress.config.ts:/cy/cypress.config.ts
     # - ./cypress/videos/:/cy/cypress/videos/
